# Generated by Django 4.2.9 on 2024-01-26 10:07

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.PositiveSmallIntegerField(choices=[(1, 'administrador'), (2, 'cliente'), (3, 'entrenador')], default=1)),
                ('groups', models.ManyToManyField(related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Deportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deporte', models.CharField(choices=[('FUT', 'Futbol'), ('BSK', 'Baloncesto'), ('PDL', 'Padel'), ('---', 'Sin_Asignar')], default='---', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('capacidad', models.IntegerField(default=1)),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.deportes', verbose_name='deporte')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=150)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('MAS', 'Masculino'), ('FEM', 'Femenino'), ('---', 'Sin_Asignar')], default='---', max_length=3)),
                ('rol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(default=0)),
                ('comentario', models.CharField(max_length=400)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('equipos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipos')),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('capacidad', models.IntegerField()),
                ('calle', models.CharField(max_length=150)),
                ('deporte', models.ManyToManyField(to='app.deportes', verbose_name='deporte')),
                ('equipo', models.ManyToManyField(to='app.equipos', verbose_name='equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Rel_Usu_Equi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipos', verbose_name='equipos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuarios', verbose_name='usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Rel_Equi_Ubi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipos', verbose_name='equipos')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ubicacion', verbose_name='ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Rel_Dep_Ubi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.deportes', verbose_name='deporte')),
                ('equipos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipos', verbose_name='equipos')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=400, validators=[django.core.validators.MinLengthValidator(limit_value=100)])),
                ('descuento', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fecha_fin_promocion', models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2024, 1, 26, 10, 7, 24, 503487, tzinfo=datetime.timezone.utc))])),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil_Publico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('deportes_fav', models.TextField()),
                ('hitos_publicos', models.TextField()),
                ('lugar_fav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ubicacion', verbose_name='lugar_fav')),
                ('usuarios', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil_Privado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historial_trayectoria', models.TextField()),
                ('incidencias', models.TextField()),
                ('hitos', models.TextField()),
                ('usuarios', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='equipos',
            name='usuario_valoracion',
            field=models.ManyToManyField(related_name='votacion_usuario', through='app.Votacion', to='app.usuarios'),
        ),
        migrations.AddField(
            model_name='equipos',
            name='usurio',
            field=models.ManyToManyField(related_name='usuario_equipo', through='app.Rel_Usu_Equi', to='app.usuarios'),
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Detalles_Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidentes', models.BooleanField()),
                ('cubierto', models.BooleanField()),
                ('ubicacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.ubicacion', verbose_name='ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Caixa', 'Caixa'), ('BBVA', 'BBVA'), ('UNICAJA', 'UNICAJA'), ('ING', 'ING')], max_length=10)),
                ('numero_cuenta', models.IntegerField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria_Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('BEN', 'Benjamin'), ('INF', 'Infatil'), ('ALE', 'Alevin'), ('CAD', 'Cadete'), ('JUN', 'Junior'), ('SEN', 'Senior')], default='SEN', max_length=3)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuarios', verbose_name='usuario')),
            ],
        ),
    ]
