# Generated by Django 3.2.23 on 2023-11-08 11:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deporte', models.CharField(choices=[('FUT', 'Futbol'), ('BSK', 'Baloncesto'), ('PDL', 'Padel'), ('---', 'Sin_Asignar')], default='---', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('capacidad', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)])),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.deportes', verbose_name='deporte')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil_Privado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historial_trayectoria', models.TextField()),
                ('incidencias', models.TextField()),
                ('hitos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=150)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('MAS', 'Masculino'), ('FEM', 'Femenino'), ('---', 'Sin_Asignar')], default='---', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(default=0)),
                ('comentario', models.CharField(max_length=400)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('equipos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipos')),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('capacidad', models.IntegerField()),
                ('calle', models.CharField(max_length=150)),
                ('deporte', models.ManyToManyField(to='app.Deportes', verbose_name='deporte')),
                ('equipo', models.ManyToManyField(to='app.Equipos', verbose_name='equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Rel_Usu_Equi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipos', verbose_name='equipos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuarios', verbose_name='usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Rel_Equi_Ubi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipos', verbose_name='equipos')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ubicacion', verbose_name='ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Rel_Dep_Ubi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.deportes', verbose_name='deporte')),
                ('equipos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipos', verbose_name='equipos')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil_Publico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('deportes_fav', models.TextField()),
                ('hitos_publicos', models.TextField()),
                ('lugar_fav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ubicacion', verbose_name='lugar_fav')),
                ('usuarios', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='equipos',
            name='usuario_valoracion',
            field=models.ManyToManyField(related_name='votacion_usuario', through='app.Votacion', to='app.Usuarios'),
        ),
        migrations.AddField(
            model_name='equipos',
            name='usurio',
            field=models.ManyToManyField(related_name='usuario_equipo', through='app.Rel_Usu_Equi', to='app.Usuarios'),
        ),
        migrations.CreateModel(
            name='Detalles_Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidentes', models.BooleanField()),
                ('cubierto', models.BooleanField()),
                ('ubicacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.ubicacion', verbose_name='ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Caixa', 'Caixa'), ('BBVA', 'BBVA'), ('UNICAJA', 'UNICAJA'), ('ING', 'ING')], max_length=10)),
                ('numero_cuenta', models.IntegerField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria_Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('BEN', 'Benjamin'), ('INF', 'Infatil'), ('ALE', 'Alevin'), ('CAD', 'Cadete'), ('JUN', 'Junior'), ('SEN', 'Senior')], default='SEN', max_length=3)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuarios', verbose_name='usuario')),
            ],
        ),
    ]
