# Generated by Django 3.2.23 on 2023-11-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='capacidad',
            field=models.IntegerField(default=1),
        ),
    ]
