# Generated by Django 4.2.8 on 2024-01-25 09:38

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='fecha_fin_promocion',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2024, 1, 25, 9, 38, 15, 755526, tzinfo=datetime.timezone.utc))]),
        ),
    ]
