# Generated by Django 4.2.8 on 2023-12-14 09:29

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_equipos_capacidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=400)),
                ('descripcion', models.CharField(max_length=400)),
                ('descuento', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fecha_fin_promocion', models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2023, 12, 14, 9, 29, 33, 406132, tzinfo=datetime.timezone.utc))])),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuarios')),
            ],
        ),
    ]
