# Generated by Django 4.2.8 on 2023-12-14 09:30

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_promocion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='fecha_fin_promocion',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2023, 12, 14, 9, 30, 19, 799915, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='nombre',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
