# Generated by Django 4.2.8 on 2023-12-16 12:39

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_promocion_fecha_fin_promocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil_privado',
            name='usuarios',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.usuarios'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promocion',
            name='fecha_fin_promocion',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2023, 12, 16, 12, 39, 9, 591726, tzinfo=datetime.timezone.utc))]),
        ),
    ]
